### ISSUE TITLE
Regarding Patch submission

### ISSUE THREAD

**Issue by PraveenPenguin** [stevegrubb/fsfuzzer#1]
Hi @stevegrubb  ,

  Need one help i want to submit some patches against fsfuzzer that bring support to test can run in powerpc-le64 linux as well , how i can please guide me 

Regards
Praveen

**Comment by stevegrubb** [comment]
Doesn't matter to me. Send me patches or a pull request. Also if this is about  config.guess and  config.sub, I should just delete those out since autogen replaces them.

**Comment by PraveenPenguin** [comment]
@stevegrubb thanks ,  created pull request #2 please have a look 
Thanks

**Comment by PraveenPenguin** [comment]
@stevegrubb if patch looks good can you please merge this , that i can use this git repo in avocado test case development

Thanks in advance !

**Comment by stevegrubb** [comment]
The files pulled in by autogen.sh have been deleted. If you have any other issues let me know.
